- convert:
    n_size: 256
    new_path: ./processed_data
  load_data:
    limit_loads: 15
    list_names:
    - Dua Lipa
    - Angelina Jolie
    - Sydney Sweeney
    - Alexa Demie
    - Emma Watson
    - Kendall Jenner
    - Bella Hadid
    - Gigi Hadid
    - Emma Stone
    path: ./dataset
  predict:
    file_path: ./photo_daria.jpg
  train:
    key_load: False
    key_process: True
    path_model: model.pkl
    random_state: 100
    test_size: 0.2
